import React, { useState, useEffect } from 'react';
import { Restaurant, MenuItem, OrderStatus, User, Order } from '../types';
import { api } from '../services/api';
import { Star, Clock, MapPin, Plus, Search, ChevronRight, CheckCircle2, Bike, Package, Minus, Trash2, ShoppingCart, ChefHat, Bell, X, Filter, History } from 'lucide-react';
import Layout from '../components/Layout';

// Map Configuration
const MAP_CONFIG = {
  restaurant: { x: 80, y: 20 },
  customer: { x: 20, y: 80 },
  speed: 0.15 
};

interface CustomerAppProps {
  user?: User; // Optional as we might use it standalone in dev, but passed from App
  onLogout: () => void;
}

const CustomerApp: React.FC<CustomerAppProps> = ({ user, onLogout }) => {
  const [view, setView] = useState<'home' | 'restaurant' | 'tracking' | 'orders' | 'cart'>('home');
  const [restaurants, setRestaurants] = useState<Restaurant[]>([]);
  const [selectedRestaurant, setSelectedRestaurant] = useState<Restaurant | null>(null);
  const [restaurantMenu, setRestaurantMenu] = useState<MenuItem[]>([]);
  const [cart, setCart] = useState<{item: MenuItem, qty: number}[]>([]);
  
  // Home View Filter State
  const [searchQuery, setSearchQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState("الكل");
  const [showFilters, setShowFilters] = useState(false);
  const [minRating, setMinRating] = useState(0);

  // Tracking State
  const [activeOrderId, setActiveOrderId] = useState<string | null>(null);
  const [activeOrder, setActiveOrder] = useState<Order | null>(null);
  const [driverPos, setDriverPos] = useState(MAP_CONFIG.restaurant);
  const [eta, setEta] = useState<string>("...");
  const [driverRotation, setDriverRotation] = useState(0);

  // Notifications State
  const [notifications, setNotifications] = useState<{id: string, title: string, message: string, time: Date}[]>([]);

  // Orders History State
  const [myOrders, setMyOrders] = useState<Order[]>([]);

  // --- API INTEGRATION ---
  useEffect(() => {
    loadRestaurants();
    loadOrders();
    const interval = setInterval(loadOrders, 5000); // Poll orders
    return () => clearInterval(interval);
  }, []);

  const loadRestaurants = async () => {
    try {
        const data = await api.getRestaurants();
        setRestaurants(data);
    } catch (e) {
        console.error("Failed to load restaurants");
    }
  };

  const loadOrders = async () => {
    try {
        const data = await api.getOrders();
        setMyOrders(data);
        
        // Update active order details if exists
        if (activeOrderId) {
            const updated = data.find(o => o.id === activeOrderId);
            if (updated) {
                 if (activeOrder && activeOrder.status !== updated.status) {
                     handleStatusNotification(updated.status);
                }
                setActiveOrder(updated);
            }
        }
    } catch (e) {
        console.error("Failed to load orders");
    }
  };

  const handleRestaurantClick = async (rest: Restaurant) => {
    setSelectedRestaurant(rest);
    try {
        const menu = await api.getMenu(rest.id);
        setRestaurantMenu(menu);
        setView('restaurant');
    } catch (e) {
        alert("Could not load menu");
    }
  };

  const addToCart = (item: MenuItem) => {
    setCart(prev => {
      const existing = prev.find(i => i.item.id === item.id);
      if (existing) {
        return prev.map(i => i.item.id === item.id ? { ...i, qty: i.qty + 1 } : i);
      }
      return [...prev, { item, qty: 1 }];
    });
  };

  const updateQty = (itemId: string, delta: number) => {
    setCart(prev => prev.map(item => {
        if (item.item.id === itemId) {
            return { ...item, qty: Math.max(0, item.qty + delta) };
        }
        return item;
    }).filter(i => i.qty > 0));
  };

  const placeOrder = async () => {
    if (!selectedRestaurant) return;

    try {
        const newOrderData: Partial<Order> = {
            restaurantId: selectedRestaurant.id,
            items: cart.map(c => ({ 
                id: '', // Generated by backend
                menuItemId: c.item.id, 
                name: c.item.name, 
                price: c.item.price, 
                quantity: c.qty 
            })),
            totalPrice: cart.reduce((sum, i) => sum + (i.item.price * i.qty), 0) + selectedRestaurant.deliveryFee
        };

        const createdOrder = await api.createOrder(newOrderData);

        setMyOrders(prev => [createdOrder, ...prev]);
        setCart([]);
        setActiveOrderId(createdOrder.id);
        setActiveOrder(createdOrder);
        setView('tracking');
        
        addNotification('تم إرسال الطلب', 'بانتظار موافقة المطعم...');
    } catch (e) {
        alert('فشل إرسال الطلب، حاول مرة أخرى');
    }
  };

  const addNotification = (title: string, message: string) => {
    const id = Date.now().toString() + Math.random().toString().slice(2, 5);
    setNotifications(prev => [{id, title, message, time: new Date()}, ...prev]);
    setTimeout(() => setNotifications(prev => prev.filter(n => n.id !== id)), 6000);
  };

  const handleStatusNotification = (status: OrderStatus) => {
    switch (status) {
        case OrderStatus.ACCEPTED:
          addNotification('تم قبول الطلب!', 'المطعم بدأ في مراجعة طلبك.');
          break;
        case OrderStatus.PREPARING:
          addNotification('جاري التحضير 👨‍🍳', 'الشيف يقوم بإعداد وجبتك الآن.');
          break;
        case OrderStatus.ON_THE_WAY:
          addNotification('خرج للتوصيل 🛵', 'السائق استلم الطلب وهو في الطريق إليك.');
          break;
        case OrderStatus.DELIVERED:
          addNotification('تم الوصول 🎉', 'السائق وصل إلى موقعك. بالعافية!');
          break;
        case OrderStatus.REJECTED:
          addNotification('عذراً', 'تم رفض الطلب من قبل المطعم.');
          break;
      }
  };

  const handleNavigation = (newView: string) => {
    if (newView === 'home') setView('home');
    if (newView === 'orders') setView('orders');
    if (newView === 'tracking') setView('tracking');
    if (newView === 'cart') setView('cart');
  };

  const goBack = () => {
    if (view === 'tracking') setView('home');
    else if (view === 'restaurant') { setView('home'); setSelectedRestaurant(null); } 
    else if (view === 'cart') setView('home');
  };

  // GPS Simulation (Visual only, when ON_THE_WAY)
  useEffect(() => {
    if (activeOrder?.status !== OrderStatus.ON_THE_WAY) return;
    const moveInterval = setInterval(() => {
        setDriverPos(prev => {
        const dx = MAP_CONFIG.customer.x - prev.x;
        const dy = MAP_CONFIG.customer.y - prev.y;
        const dist = Math.sqrt(dx*dx + dy*dy);
        const mins = Math.ceil((dist / 85) * 12); 
        setEta(dist < 5 ? "أقل من دقيقة" : `${mins} دقيقة`);
        if (dist < 0.5) return MAP_CONFIG.customer;
        const angle = Math.atan2(dy, dx);
        setDriverRotation((angle * 180) / Math.PI);
        return {
            x: prev.x + Math.cos(angle) * MAP_CONFIG.speed,
            y: prev.y + Math.sin(angle) * MAP_CONFIG.speed
        };
        });
    }, 50); 
    return () => clearInterval(moveInterval);
  }, [activeOrder?.status]);

  const cartTotal = cart.reduce((sum, i) => sum + (i.item.price * i.qty), 0);
  const deliveryFee = selectedRestaurant?.deliveryFee || 0;
  const grandTotal = cartTotal + deliveryFee;

  // Render Logic (simplified for brevity in this specific update, keeping structure)
  // ... (keeping existing render logic but using API data)

  const renderContent = () => {
    // 1. TRACKING VIEW
    if (view === 'tracking') {
      if (!activeOrder) {
          return (
             <div className="flex flex-col items-center justify-center h-[70vh] text-center p-6">
                <div className="bg-gray-100 p-6 rounded-full mb-4"><Package size={48} className="text-gray-400" /></div>
                <h2 className="text-xl font-bold text-gray-800">لا يوجد طلب نشط</h2>
                <button onClick={() => setView('home')} className="mt-6 bg-red-600 text-white px-6 py-2 rounded-lg font-bold">تصفح المطاعم</button>
             </div>
          )
      }

      return (
        <div className="flex flex-col h-full bg-gray-50 pb-20 lg:pb-0">
          <div className="bg-white p-4 shadow-sm z-20 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <button onClick={() => setView('home')} className="p-2 hover:bg-gray-100 rounded-full transition"><ChevronRight size={24} className="text-gray-600" /></button>
              <div>
                 <h1 className="font-bold text-gray-800">تتبع الطلب</h1>
                 <p className="text-xs text-gray-500">#{activeOrder.id.substring(0, 8)}</p>
              </div>
            </div>
            <div className={`px-3 py-1 rounded-full text-xs font-bold ${activeOrder.status === OrderStatus.DELIVERED ? 'bg-green-100 text-green-700' : 'bg-red-50 text-red-600'}`}>
              {activeOrder.status === OrderStatus.DELIVERED ? 'مكتمل' : 'نشط'}
            </div>
          </div>
  
          <div className="flex-1 flex flex-col lg:flex-row overflow-hidden relative">
            <div className="flex-1 bg-[#f3f4f6] relative overflow-hidden min-h-[45vh] lg:min-h-full group">
               <div className="absolute inset-0 pointer-events-none">
                   {/* Simplified Map Visualization */}
                   <div className="w-full h-full flex items-center justify-center text-gray-300">Google Maps Integration Required</div>
               </div>
            </div>
            <div className="bg-white w-full lg:w-96 shadow-[0_-5px_20px_rgba(0,0,0,0.1)] rounded-t-3xl lg:rounded-none z-10 flex flex-col max-h-[55vh] lg:max-h-full overflow-y-auto relative">
               <div className="p-6 border-b bg-gradient-to-b from-white to-gray-50">
                  <div className="flex justify-between items-start mb-4">
                     <div><p className="text-gray-500 text-sm font-medium">وقت الوصول المتوقع</p><h2 className="text-3xl font-extrabold text-gray-900 tracking-tight mt-1">{activeOrder.status === OrderStatus.ON_THE_WAY ? eta : '--'}</h2></div>
                     {activeOrder.status === OrderStatus.ON_THE_WAY && <div className="w-10 h-10 bg-red-50 text-red-600 rounded-full flex items-center justify-center animate-bounce-short"><Bike size={20} /></div>}
                  </div>
                  <div className="w-full bg-gray-200 h-2 rounded-full overflow-hidden">
                     <div className="bg-red-600 h-full transition-all duration-1000 ease-out" style={{ width: activeOrder.status === OrderStatus.PENDING ? '5%' : activeOrder.status === OrderStatus.PREPARING ? '35%' : activeOrder.status === OrderStatus.ON_THE_WAY ? '75%' : activeOrder.status === OrderStatus.DELIVERED ? '100%' : '0%' }}></div>
                  </div>
                  <p className="text-xs text-gray-400 mt-2 text-left dir-ltr">
                     {activeOrder.status}
                  </p>
               </div>
               <div className="p-6 pt-2 space-y-6">
                {[
                    { s: OrderStatus.PENDING, label: 'تم إرسال الطلب', icon: <CheckCircle2 size={16} /> },
                    { s: OrderStatus.PREPARING, label: 'المطعم يجهز طلبك', icon: <ChefHat size={16} /> },
                    { s: OrderStatus.ON_THE_WAY, label: 'خرج للتوصيل', icon: <Bike size={16} /> },
                    { s: OrderStatus.DELIVERED, label: 'تم التسليم', icon: <MapPin size={16} /> }
                ].map((step, idx) => {
                     const isCompleted = 
                        (activeOrder.status === OrderStatus.DELIVERED) ||
                        (activeOrder.status === OrderStatus.ON_THE_WAY && idx <= 2) ||
                        (activeOrder.status === OrderStatus.READY && idx <= 1) ||
                        (activeOrder.status === OrderStatus.PREPARING && idx <= 1) ||
                        (activeOrder.status === OrderStatus.PENDING && idx === 0) || 
                        (activeOrder.status === OrderStatus.ACCEPTED && idx === 0);
                     const isActive = activeOrder.status === step.s || (activeOrder.status === OrderStatus.ACCEPTED && idx === 0) || (activeOrder.status === OrderStatus.READY && idx === 1);
                     return (
                        <div key={idx} className="flex gap-4 items-start relative group">
                           {idx < 3 && <div className="absolute top-8 right-[19px] w-0.5 h-full bg-gray-100 group-last:hidden"></div>}
                           <div className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 z-10 transition-all duration-500 ${isCompleted || isActive ? 'bg-red-600 text-white shadow-lg shadow-red-200' : 'bg-gray-100 text-gray-400'}`}>
                              {isActive ? <div className="animate-pulse">{step.icon}</div> : step.icon}
                           </div>
                           <div className="pt-2"><h4 className={`text-sm ${isCompleted || isActive ? 'font-bold text-gray-900' : 'font-medium text-gray-400'}`}>{step.label}</h4></div>
                        </div>
                     )
                })}
               </div>
            </div>
          </div>
        </div>
      );
    }

    if (view === 'restaurant' && selectedRestaurant) {
      return (
        <div className="pb-24">
          <div className="relative h-48 lg:h-64 w-full bg-gray-200 rounded-b-xl lg:rounded-xl overflow-hidden mb-6">
             <img src="https://picsum.photos/800/400" className="w-full h-full object-cover" alt="Cover" />
             <button onClick={goBack} className="absolute top-4 right-4 bg-white rounded-full p-2 shadow-lg hover:bg-gray-100 transition"><span className="text-xl font-bold px-1">&rarr;</span></button>
          </div>
          <div className="px-4 -mt-12 relative z-10 lg:mt-0 lg:px-0 lg:mb-6">
            <div className="bg-white rounded-xl shadow-lg p-4 lg:p-6">
               <div className="flex justify-between items-start">
                 <div><h1 className="text-2xl font-bold mb-1">{selectedRestaurant.name}</h1><div className="flex items-center text-sm text-gray-500 gap-4"><span className="flex items-center gap-1"><Star size={14} className="text-yellow-400 fill-current" /> 4.5</span><span className="flex items-center gap-1"><Clock size={14} /> 30-45 د</span></div></div>
                 <div className="w-16 h-16 bg-gray-100 rounded-lg overflow-hidden border"><img src={selectedRestaurant.logo} alt="Logo" className="w-full h-full object-cover" /></div>
               </div>
            </div>
          </div>
          <div className="p-4 lg:p-0">
            <h2 className="font-bold text-lg mb-4">القائمة</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
              {restaurantMenu.map(item => (
                <div key={item.id} className="flex gap-4 p-3 bg-white rounded-lg shadow-sm border border-gray-100 hover:shadow-md transition">
                   <img src={item.image} alt={item.name} className="w-24 h-24 rounded-lg object-cover bg-gray-100" />
                   <div className="flex-1 flex flex-col justify-between">
                     <div><h3 className="font-bold text-gray-800 line-clamp-1">{item.name}</h3><p className="text-xs text-gray-400">{item.category}</p></div>
                     <div className="flex justify-between items-end"><span className="font-bold text-red-600">{item.price.toLocaleString()} د.ع</span><button onClick={() => addToCart(item)} className="w-8 h-8 rounded-full bg-red-50 text-red-600 flex items-center justify-center hover:bg-red-600 hover:text-white transition"><Plus size={18} /></button></div>
                   </div>
                </div>
              ))}
            </div>
          </div>
          {cart.length > 0 && (
            <div onClick={() => setView('cart')} className="fixed bottom-24 lg:bottom-10 left-4 right-4 lg:left-auto lg:right-10 lg:w-96 bg-red-600 text-white p-4 rounded-xl shadow-xl flex justify-between items-center z-40 animate-bounce-short cursor-pointer hover:bg-red-700 transition">
              <div className="flex items-center gap-2"><div className="bg-white text-red-600 w-8 h-8 rounded-full flex items-center justify-center font-bold">{cart.reduce((a, b) => a + b.qty, 0)}</div><span className="font-bold">عرض السلة</span></div>
              <div className="flex items-center gap-4"><span className="font-bold text-lg">{cartTotal.toLocaleString()} د.ع</span><span className="text-sm opacity-90">&larr;</span></div>
            </div>
          )}
        </div>
      );
    }

    if (view === 'cart') {
      if (cart.length === 0) return (<div className="flex flex-col items-center justify-center h-[70vh] text-center p-6"><div className="bg-gray-100 p-6 rounded-full mb-4"><ShoppingCart size={48} className="text-gray-400" /></div><h2 className="text-xl font-bold text-gray-800">السلة فارغة</h2><button onClick={() => setView('home')} className="mt-6 bg-red-600 text-white px-6 py-2 rounded-lg font-bold">تصفح المطاعم</button></div>);
      return (
        <div className="space-y-6 pb-24">
          <div className="flex items-center gap-3 px-1"><button onClick={() => setView('home')} className="p-2 hover:bg-gray-200 rounded-full bg-white shadow-sm"><ChevronRight /></button><h2 className="text-2xl font-bold text-gray-800">سلة المشتريات</h2></div>
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
            {cart.map((cartItem, idx) => (
              <div key={idx} className="flex gap-4 p-4 border-b last:border-0">
                <img src={cartItem.item.image} alt={cartItem.item.name} className="w-20 h-20 rounded-lg object-cover bg-gray-100" />
                <div className="flex-1 flex flex-col justify-between">
                  <div><h3 className="font-bold text-gray-900">{cartItem.item.name}</h3><p className="text-xs text-gray-500">{cartItem.item.category}</p></div>
                  <div className="flex justify-between items-center">
                    <span className="font-bold text-red-600">{(cartItem.item.price * cartItem.qty).toLocaleString()} د.ع</span>
                    <div className="flex items-center gap-3 bg-gray-50 rounded-lg p-1"><button onClick={() => updateQty(cartItem.item.id, -1)} className="w-6 h-6 flex items-center justify-center bg-white rounded shadow-sm text-gray-600 hover:text-red-600">{cartItem.qty === 1 ? <Trash2 size={14} /> : <Minus size={14} />}</button><span className="text-sm font-bold w-4 text-center">{cartItem.qty}</span><button onClick={() => updateQty(cartItem.item.id, 1)} className="w-6 h-6 flex items-center justify-center bg-white rounded shadow-sm text-green-600"><Plus size={14} /></button></div>
                  </div>
                </div>
              </div>
            ))}
          </div>
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-4 space-y-3">
             <div className="flex justify-between text-gray-600"><span>المجموع الفرعي</span><span>{cartTotal.toLocaleString()} د.ع</span></div>
             <div className="flex justify-between text-gray-600"><span>رسوم التوصيل</span><span>{deliveryFee.toLocaleString()} د.ع</span></div>
             <div className="border-t pt-3 flex justify-between font-bold text-lg text-gray-900"><span>الإجمالي الكلي</span><span>{grandTotal.toLocaleString()} د.ع</span></div>
          </div>
          <button onClick={placeOrder} className="w-full bg-red-600 text-white py-4 rounded-xl font-bold shadow-lg hover:bg-red-700 transition flex justify-center items-center gap-2"><span>تأكيد الطلب</span><CheckCircle2 size={20} /></button>
        </div>
      );
    }

    if (view === 'orders') {
      return (
        <div className="space-y-6">
          <h2 className="text-2xl font-bold text-gray-800 px-1">طلباتي السابقة</h2>
          <div className="space-y-4">
            {myOrders.map((order) => (
              <div key={order.id} onClick={() => { setActiveOrder(order); setActiveOrderId(order.id); setView('tracking'); }} className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 cursor-pointer hover:shadow-md transition">
                <div className="flex justify-between items-start mb-4">
                  <div><h3 className="font-bold text-lg">{order.restaurantName}</h3><p className="text-xs text-gray-500">{new Date(order.createdAt).toLocaleDateString()} • {new Date(order.createdAt).toLocaleTimeString()}</p></div>
                  <span className={`px-2 py-1 rounded text-xs font-bold ${order.status === OrderStatus.DELIVERED ? 'bg-green-100 text-green-700' : 'bg-blue-100 text-blue-700'}`}>{order.status}</span>
                </div>
                <div className="flex justify-between items-center border-t pt-3">
                  <span className="font-bold text-lg">{order.totalPrice.toLocaleString()} د.ع</span>
                  <button className="text-red-600 text-sm font-bold flex items-center gap-1"><History size={16} /> تتبع</button>
                </div>
              </div>
            ))}
             {myOrders.length === 0 && <p className="text-center text-gray-400 py-10">لا توجد طلبات سابقة</p>}
          </div>
        </div>
      );
    }

    // HOME VIEW (Default)
    return (
      <div className="space-y-6 pb-20 lg:pb-0">
        <div className="flex gap-2 items-center">
            <div className="relative flex-1"><input type="text" value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="ابحث عن مطعم أو أكلة..." className="w-full bg-white p-4 pr-12 rounded-xl shadow-sm border-none outline-none text-gray-700 focus:ring-2 focus:ring-red-100 transition" /><Search className="absolute top-4 right-4 text-gray-400" size={20} /></div>
            <button onClick={() => setShowFilters(!showFilters)} className={`p-4 rounded-xl shadow-sm transition ${showFilters ? 'bg-red-600 text-white' : 'bg-white text-gray-600'}`}><Filter size={20} /></button>
        </div>
        <div>
          <h2 className="font-bold text-lg mb-3 px-1">المطاعم ({restaurants.length})</h2>
          {restaurants.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                {restaurants.map(rest => (<div key={rest.id} onClick={() => handleRestaurantClick(rest)} className="bg-white rounded-xl shadow-sm overflow-hidden border border-gray-100 hover:shadow-md cursor-pointer transition-all duration-200 group"><div className="h-40 bg-gray-200 relative overflow-hidden"><img src={rest.logo || `https://picsum.photos/seed/${rest.id}/500/200`} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" alt="Restaurant" />{!rest.isOpen && <div className="absolute inset-0 bg-black/60 flex items-center justify-center"><span className="text-white font-bold border border-white px-3 py-1 rounded">مغلق حالياً</span></div>}</div><div className="p-4"><div className="flex justify-between items-start mb-1"><h3 className="font-bold text-lg text-gray-900">{rest.name}</h3><span className="bg-green-100 text-green-700 text-xs px-2 py-1 rounded-full font-bold flex items-center gap-1"><Star size={10} className="fill-current" /> 4.5</span></div><div className="flex items-center justify-between mt-3 text-sm text-gray-500"><div className="flex gap-3"><span className="flex items-center gap-1"><MapPin size={14} /> 1.2 كم</span><span className="flex items-center gap-1"><Clock size={14} /> 30 د</span></div><span className="text-red-600 font-bold bg-red-50 px-2 py-1 rounded text-xs">{rest.deliveryFee > 0 ? `توصيل ${rest.deliveryFee}` : 'توصيل مجاني'}</span></div></div></div>))}
            </div>
          ) : (<div className="text-center py-10 text-gray-500"><p>لا توجد مطاعم متاحة حالياً.</p></div>)}
        </div>
      </div>
    );
  };

  return (
    <Layout user={user || { id: 'guest', name: 'Guest', role: 'customer' } as User} onLogout={onLogout} title="الرئيسية" activeView={view} onNavigate={handleNavigation}>
      <div className="fixed top-4 left-4 right-4 z-[60] flex flex-col gap-2 pointer-events-none">
        {notifications.map(n => (
          <div key={n.id} onClick={() => { setView('tracking'); setNotifications(prev => prev.filter(x => x.id !== n.id)); }} className="bg-gray-900 text-white p-4 rounded-xl shadow-2xl transform transition-all animate-in slide-in-from-top-4 duration-300 pointer-events-auto cursor-pointer flex items-center gap-4 max-w-md mx-auto w-full">
             <div className="w-10 h-10 rounded-full bg-red-600 flex items-center justify-center shrink-0"><Bell size={20} className="animate-pulse" /></div>
             <div className="flex-1"><h4 className="font-bold text-sm">{n.title}</h4><p className="text-xs text-gray-300">{n.message}</p></div>
             <button onClick={(e) => { e.stopPropagation(); setNotifications(prev => prev.filter(x => x.id !== n.id)); }} className="text-gray-400 hover:text-white"><X size={16} /></button>
          </div>
        ))}
      </div>
      {renderContent()}
    </Layout>
  );
};

export default CustomerApp;